### ISSUE TITLE
为什么cn和en要各自独立建立一个repo?

### ISSUE THREAD

**Issue by chengjun** [yihui/cn#1]
为什么cn要建立在yuihui.github.io这个repo之外？我今天尝试在yuihui.github.io这个repo里建立一个子文件夹blog, 却失败了。

抱歉，这个问题可能被我重复问过了。

**Comment by yihui** [comment]
理论上应该是可以放在一起的，但就得在模板文件里写上一些判断语句，另外还不方便自定义 yihui.name/cn /en这样的路径（理论上应该也是可能的）。总之，因为本来也是两个独立的网站，就分开了。

**Comment by chengjun** [comment]
多谢回复。

我发现之后放在子文件夹blog中会失败，但是如果将blog这个folder中的内容拿出来放在第一层文件夹中就可以。jekyll可以识别博客路径到repo（一般的repo和博客repo无差别）的第一层。以yihui.name/cn/en作为例子， yihui.name/cn/en这样的路径可能实现是通过：
1. 把cn中内容放在yihui.name这个repo的第一层，将cn的index放在一个叫cn的文件夹里（此处区分首页index与博客index），但cn中其它文件都取出放在第一层（所以第一层会有很多文件夹）。
2. 但是en无法放入这个repo中，en必须重新建立一个新的repo。

**Comment by yihui** [comment]
2017 年初我将两个库的内容用 Hugo 大一统到一个库中了：https://github.com/yihui/yihui.org
