### ISSUE TITLE
cn/_config.yml  using the 'redcarpet' Markdown engine

### ISSUE THREAD

**Issue by JPingAMMS** [yihui/cn#4]
When I fork your page and change the web address to my github.io address, I recieved an Email warning "using the **'redcarpet'** Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. " AND another Email warning "use the **'pygments'** highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead."

These warnings are in cn/_config.yml. Perhaps some guy which forks this repo would be confused for a second.

I guess you may already know that because of the changes in your homepage _config.yml...

**Comment by yihui** [comment]
Yes I'm aware of these issues. redcarpet should be kramdown, and pygments should be rouge now. I have not updated this repo for a long time. Thanks!
