### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by kingofctrl** [yihui/cn#5]
建议将模板提取出来重新建个仓库，然后再起个拉风的名字，方便推荐。

ps. 这个模板很漂亮，我带走了（逃

**Comment by yihui** [comment]
你给我站住，你挖的坑你来填

土遁！土流壁！[）](http://pic.hanhande.com/files/allimg/070531/1616553.gif)

**Comment by kingofctrl** [comment]
模板已经用上了， hmybmny.com 
如果你时间不充裕的话你建个仓库我给你提PR？

**Comment by yihui** [comment]
就喜欢你这种一言不合就提 PR 的。不用 PR 了，直接上：https://github.com/yihui/great-waterfall 睡觉去了，明早起来验货 😎

**Comment by kingofctrl** [comment]
货物已妥投

**Comment by yihui** [comment]
厉害了我的哥，你动作这么快你家里人造吗？这两天略忙，过两天再细验，初看没啥问题

**Comment by yihui** [comment]
我已经[告别 Jekyll](https://yihui.name/cn/2017/02/kaiti/)又搬家了，新网站基于 Hugo，新模板在 https://github.com/yihui/hugo-lithium-theme 你要是有兴趣把旧网站的模板转移到 Hugo 框架下，我也非常欢迎。
